language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

before_script:
  - redis-server tests/fixtures/redis.conf

after_success:
  - curl https://markov-chain.github.io/travis/documentation.sh | CARGO_FLAGS="--features=caching" bash

script:
  - cargo build --verbose
  - cargo test --features=caching --verbose -- --nocapture

env:
  global:
    - secure: bg6hmZaSzYP8aANzrxH+QoqKOoEziJS7sdRynB7wmIslTAIJosy+FRlWqWzomXeonSIdEKy6MAnFHJnuZdQ8gdsd66wjkKNKrGxW8s5XQNY9A9+b4IbMGSVH8ZhDwrk3YNGTNHST8W83TOpE7Vmbd1MQrSkaV7EmBxR07XUVJn+EXP9FyeVZPOCjy3AvrDY+rAVz1cahwAM4rIuMbN7JcaSXD7lRjWShBJTI0ysvFkj123gdtdMC1QiBhfkO10kNJfVIheAO501C9Xi9e1CWeqj6IFfMjlpyAHhhz2GoF7XwlGvFKEaBi6VNaqne+0uvSGpnQ2dt/ivLaDa5Qq65TOUCFztNGSZkM6f/v8O1r5xcj4X9GOdOsjvwuO7XJoLlZQMKARVUdJQWjvPgG6lglmy/0jMurwMVSlAfY56CqO14qI1C1eKGfI1O0hixxchuUh99tLM24HskYEr0sBH37uOxe53SVj2vbw/WyNSNICDLJtcGkLrfu2mxqhBdYfKXn9rJdeSKUCfvRtXrkOSJYmVj2q8UJWjut3FejLzTPfINVaRHDMM6XusmmZHaRiAhZpj4wA1eKtNxXCf+ZeaEwZ4KIosh52L9bF7oxcdC/luH9PDMdBiR9yryoKDRMQoUNoR125rsOqb5JVo6bGG2wSdauQuqxLGC9VvCaT9n110=

notifications:
  email: false
