[package]
name = "mcpat"
version = "0.1.5"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/mcpat"
homepage = "https://github.com/stainless-steel/mcpat"
documentation = "https://stainless-steel.github.io/mcpat"
description = "The package provides an interface to McPAT."

[dependencies]
libc = "*"
mcpat-sys = "*"
